### ISSUE TITLE
Airlock/Structural part masses

### ISSUE THREAD

**Issue by jmrd98** [MrMeeb/Shuttle-Payload-Technologies#1]
Logging an issue as requested: The main issue is the new airlock massing in at 7 tons, vs perhaps 1 ton. I'll mention the structural parts, but I don't know if they are out of sorts. Gameplay wise, I would look for them to be somewhat low in mass, while the lab itself was the bulk. This may also help balancing the cargo bay. 

But I'm not the one driving the bus/mod of course ;)

**Comment by MrMeeb** [comment]
Fixed in v0.21 Dev. Look a bit more reasonable now!
